services:
  api:
    build: ./Go
    ports:
      - "8080:8080"
    networks:
      - redMVC
    depends_on:
      - db
    #links:
    #  - api


  db:
    build: ./Postgres
    networks:
      - redMVC
    ports:
      - "5432:5432"
    #links:
    #  - db

  frontend:
    build: ./Node
    ports:
      - "3000:3000"
    networks:
      - redMVC
    depends_on:
      - api


networks:
  redMVC:
    driver: bridge

